name: Format

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@24.3.0
      - uses: isort/isort-action@v1
        with:
          isort-version: "5.12.0"
